# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stage: Build
  jobs:
    job: Build

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run build'
  inputs:
    command: 'build'
    projects: '/Mkss.Domainr.Core/Mkss.Domainr.Core.csproj'
    workingDirectory: 'src/Core'
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '/Mkss.Domainr.Core/Mkss.Domainr.Core.Tests.csproj'
    workingDirectory: 'src/Core'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'