# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/Core/Mkss.Domainr.Core
      - src/Core/Mkss.Domainr.Core.Tests
    exclude:
      - src/Core/README.md

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run Restore'
  inputs:
    command: 'restore'
    projects: |
      src/Core/Mkss.Domainr.Core/Mkss.Domainr.Core.csproj
      src/Core/Mkss.Domainr.Core.Tests/Mkss.Domainr.Core.Tests.csproj
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'Run build'
  inputs:
    command: 'build'
    projects: 'src/Core/Mkss.Domainr.Core/Mkss.Domainr.Core.csproj'
    arguments: --configuration $(BuildConfiguration)
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: 'src/Core/Mkss.Domainr.Core.Tests/Mkss.Domainr.Core.Tests.csproj'
    arguments: --configuration $(BuildConfiguration)
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/Core/Mkss.Domainr.Core/Mkss.Domainr.Core.csproj'
    packDestination: 'src/Core/Mkss.Domainr.Core/bin/$(BuildConfiguration)/netstandard2.0'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: 'src/Core/Mkss.Domainr.Core/bin/$(BuildConfiguration)/netstandard2.0'
    ArtifactName: 'drop'
    publishLocation: 'Container'